[slack]
#https://get.slack.help/hc/en-us/articles/212281468-Direct-messages-and-group-DMs
#Only join multiple person Direct messages when someone talks. This stops from cluttering your 
#irc client with lots of windows.
JoinMpImOnTalk = true
